name: Unit Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install gdal 
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install libgdal-dev osmctools gdal-bin libspatialindex-dev
         
      - name: Install Dependencies
        run: |

          python -m pip install --upgrade pip
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          pip install nose
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          make test